services:
  tangerines_auction_web:
    image: tangerines_auction_web
    build:
      context: .
      dockerfile: TangerinesAuction.Web/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__TADbContext=User ID=postgres;Password=123;Host=database;Port=5432;Database=ta;
    networks:
      - ta_network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "ta"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ta_network

networks:
  ta_network:
    driver: bridge

volumes:
  postgres_data:
